package one.gypsy.neatorganizer.database.entity.notes

import androidx.room.Entity
import androidx.room.PrimaryKey
import one.gypsy.neatorganizer.database.entity.Timestamped

/**
 * Represents a note entity in the "notes" table of the database.
 * This data class holds the data for a single note, including its title, content, and associated metadata.
 *
 * @property id The unique identifier for the note. Automatically generated by the database.
 * @property title The title of the note.
 * @property content The content of the note, defaulting to an empty string if not provided.
 * @property createdAt The timestamp when the note was created. This field is inherited from the [Timestamped] interface.
 * @property color The color associated with the note, represented as an integer.
 */
@Entity(tableName = "notes")
data class NoteEntity(
    @PrimaryKey(autoGenerate = true) var id: Long = 0,
    val title: String,
    val content: String = "",
    override val createdAt: Long,
    val color: Int
) : Timestamped

