// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
}

    dependencies {
        classpath "com.android.tools.build:gradle:${Version.gradleVersion}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${Version.kotlinVersion}"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:${Version.nav_version}"
    }
}

plugins {
    id 'org.jetbrains.dokka' version '1.4.30'
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com'}
        maven { url 'https://jitpack.io' }
        maven { url "https://dl.bintray.com/kotlin/dokka/" }
        maven { url "https://dl.bintray.com/kotlin/kotlinx" }
        maven { url "https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven" }
    }
}

subprojects {
    apply plugin: 'org.jetbrains.dokka'
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
