package one.gypsy.neatorganizer.database.entity.tasks

import androidx.room.Entity
import androidx.room.PrimaryKey
import one.gypsy.neatorganizer.database.entity.Timestamped
import one.gypsy.neatorganizer.database.entity.tasks.SingleTaskGroupEntity.Companion.TABLE_NAME

/**
 * Represents a single task group entity in the "single_task_group" table of the database.
 * This data class holds the data for a group of single tasks, including its name and creation timestamp.
 *
 * @property name The name of the task group.
 * @property id The unique identifier for the task group. Automatically generated by the database.
 * @property createdAt The timestamp when the task group was created. This field is inherited from the [Timestamped] interface.
 *
 * The companion object contains constants for the table and column names used in the database.
 */
@Entity(tableName = TABLE_NAME)
data class SingleTaskGroupEntity(
    val name: String,

    @PrimaryKey(autoGenerate = true) var id: Long = 0,

    override val createdAt: Long
) : Timestamped {
    companion object {
        const val TABLE_NAME = "single_task_group"
        const val NAME_FIELD = "name"
        const val CREATED_AT_FIELD = "createdAt"
    }
}

