package one.gypsy.neatorganizer.database.entity.tasks

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.ForeignKey.CASCADE
import androidx.room.PrimaryKey
import one.gypsy.neatorganizer.database.entity.Timestamped

/**
 * Represents a single task entity in the "single_tasks" table of the database.
 * This data class holds the data for an individual task, including its name, completion status,
 * and the task group it belongs to.
 *
 * @property id The unique identifier for the single task. Automatically generated by the database.
 * @property groupId The unique identifier for the task group this task belongs to. This is a foreign key referencing the [SingleTaskGroupEntity].
 * @property name The name of the task.
 * @property done A boolean flag indicating whether the task is marked as completed.
 * @property createdAt The timestamp when the task was created. This field is inherited from the [Timestamped] interface.
 *
 * The `groupId` serves as the foreign key linking this task to a specific task group in the `single_task_group` table.
 */
@Entity(
    tableName = "single_tasks",
    foreignKeys = [
        ForeignKey(
            entity = SingleTaskGroupEntity::class,
            parentColumns = ["id"],
            childColumns = ["groupId"],
            onDelete = CASCADE,
            onUpdate = CASCADE
        )
    ]
)
data class SingleTaskEntity(
    @PrimaryKey(autoGenerate = true) var id: Long = 0,
    val groupId: Long,
    val name: String,
    val done: Boolean,
    override val createdAt: Long
) : Timestamped

