apply from: Dependencies.common

dependencies {
    implementation Glide.glide
    annotationProcessor Glide.compiler

    testImplementation Mockk.mockk

    implementation View.autoFitEditText

    implementation Lifecycle.runtime
    implementation Lifecycle.viewmodel
    implementation Lifecycle.ext
    implementation Lifecycle.livedata

    implementation Navigation.fragment
    implementation Navigation.ui

    implementation WorkManager.runtime

    implementation View.constraintLayout

    implementation View.material
}