package one.gypsy.neatorganizer.database.entity.routines

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import one.gypsy.neatorganizer.database.entity.Timestamped

/**
 * Represents a routine task entity in the "routine_tasks" table of the database.
 * This data class holds the data for a specific task within a routine, including its name,
 * completion status, and the routine it is associated with.
 *
 * @property name The name of the task.
 * @property done A boolean flag indicating whether the task is marked as completed.
 * @property routineId The unique identifier for the routine this task belongs to. This is a foreign key referencing the [RoutineEntity].
 * @property id The unique identifier for the routine task. Automatically generated by the database.
 * @property createdAt The timestamp when the task was created. This field is inherited from the [Timestamped] interface.
 *
 * The `routineId` serves as the foreign key linking this task to a specific routine in the `routines` table.
 */
@Entity(
    tableName = "routine_tasks",
    foreignKeys = [
        ForeignKey(
            entity = RoutineEntity::class,
            parentColumns = ["id"],
            childColumns = ["routineId"],
            onDelete = ForeignKey.CASCADE,
            onUpdate = ForeignKey.CASCADE
        )
    ]
)
data class RoutineTaskEntity(
    val name: String,
    val done: Boolean,
    val routineId: Long,

    @PrimaryKey(autoGenerate = true) var id: Long = 0,

    override val createdAt: Long
) : Timestamped

