package one.gypsy.neatorganizer.database.entity.routines

import androidx.room.Entity
import androidx.room.PrimaryKey
import one.gypsy.neatorganizer.database.entity.Timestamped

/**
 * Represents a routine entity in the "routines" table of the database.
 * This data class holds the data for a single routine, including its name and creation timestamp.
 *
 * @property name The name of the routine.
 * @property id The unique identifier for the routine. Automatically generated by the database.
 * @property createdAt The timestamp when the routine was created. This field is inherited from the [Timestamped] interface.
 */
@Entity(tableName = "routines")
data class RoutineEntity(
    val name: String,

    @PrimaryKey(autoGenerate = true) var id: Long = 0,

    override val createdAt: Long
) : Timestamped

