package one.gypsy.neatorganizer.database.entity.routines.reset

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Represents a snapshot of routines in the "routine_snapshots" table of the database.
 * This entity stores the date when the routines were last reset.
 *
 * @property routinesResetDate The date when the routines were last reset.
 * @property routineSnapshotId The unique identifier for the routine snapshot. Automatically generated by the database.
 */
@Entity(tableName = "routine_snapshots")
data class RoutineSnapshotEntity(
    val routinesResetDate: Date,

    @PrimaryKey(autoGenerate = true) var routineSnapshotId: Long = 0
)

