apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: "androidx.navigation.safeargs.kotlin"

apply from: Dependencies.dependency

android {

    dataBinding {
        enabled = true
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    compileSdkVersion Version.compileSdkVersion

    defaultConfig {
        applicationId "one.gypsy.neatorganizer"
        minSdkVersion Version.minSdkVersion
        targetSdkVersion Version.targetSdkVersion
        versionCode Version.versionCode
        versionName Version.versionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    // work-runtime-ktx 2.1.0 and above now requires Java 8
    kotlinOptions {
        jvmTarget = Version.jvmTarget
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    dependencies {
        implementation project(':swipemenu')
        implementation project(':materialintro')
        implementation project(':routine')
        implementation project(':note')
        implementation project(':task')
        implementation project(':core')
        implementation project(':data')
        implementation project(':database')
        implementation project(':domain')
        implementation project(':tutorial')

        implementation 'io.insert-koin:koin-android:2.1.6'
        implementation 'io.insert-koin:koin-core-ext:2.1.6'
        implementation 'io.insert-koin:koin-android:2.1.6'
        implementation 'io.insert-koin:koin-test:2.1.6'
        implementation 'io.insert-koin:koin-android-viewmodel:2.1.6'
//        implementation 'com.github.shripal17:MaterialIntroView-v2:2.2.0'
    }
}

