apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

apply from: Dependencies.dependency


java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

android {
    compileSdkVersion Version.compileSdkVersion

    defaultConfig {
        targetSdkVersion Version.targetSdkVersion
        minSdkVersion Version.minSdkVersion
    }
}

dependencies {
    implementation project(':database')
}