apply from: Dependencies.common

dependencies {
    kapt Room.compiler
    implementation Room.ktx
    implementation Room.runtime
    testImplementation Room.testing

    testImplementation TestUtils.core
    testImplementation Junit.junit
    androidTestImplementation TestUtils.core
    androidTestImplementation TestUtils.runner
    testImplementation AssertJ.core
    androidTestImplementation AssertJ.core

    implementation Lifecycle.livedata
    implementation Lifecycle.ext
    implementation Lifecycle.runtime

    implementation Koin.core
    implementation Koin.core_ext
}
